spring:
  jmx:
    default-domain: com.a6raywa1cher.javahackraiffemulator
    unique-names: true
# ===============================
# DB CONNECTION
# ===============================
spring.datasource.url: jdbc:postgresql://localhost:5433/javahack-raiff-emulator
spring.datasource.username: postgres
spring.datasource.password: postgres
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate.default_schema: public
spring.jpa.properties.hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false